name: Test

on:
  push:
    tags-ignore:
      - '**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v7
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache-dependency-path: |
            go.sum
            store/redis/go.sum
      - name: Install dependencies
        run: |
          go mod download
          go -C store/redis mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=5m --issues-exit-code 1 --path-mode abs --output.checkstyle.path ${{ github.workspace }}/golangci-lint-report.out ./...
      - name: golangci-lint Redis
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: store/redis
          args: --timeout=5m --issues-exit-code 1 --path-mode abs --output.checkstyle.path ${{ github.workspace }}/store/redis/golangci-lint-report.out ./...
      - name: Run tests
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out -json ./... > test-report.out
      - name: Run Redis unit and Valkey integration tests
        working-directory: store/redis
        run: |
          go test -race -count=1 -timeout=5m -covermode=atomic -coverprofile=coverage.out -json ./... > test-report.out
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8
        with:
          args: >
            -Dsonar.organization=${{ github.repository_owner }}
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ env.REPOSITORY_NAME }}
            -Dsonar.go.coverage.reportPaths=coverage.out,store/redis/coverage.out
            -Dsonar.go.tests.reportPaths=test-report.out,store/redis/test-report.out
            -Dsonar.go.golangci-lint.reportPaths=golangci-lint-report.out,store/redis/golangci-lint-report.out
            -Dsonar.sources=.
            -Dsonar.exclusions=**/vendor/**,**/*_test.go,example/**
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
